### PR TITLE
chore: source a Cargo.lock in ffi crate to help Nix build it

### PR DESCRIPTION
**Pull request by beltram**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

In order for Nix to deterministically build the ffi crate, it requires a Cargo.lock. We create it through a build script because we do not want it in the main workspace since this is primarily a lib

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by flokli** [comment]
Thanks! This almost works, but the Cargo.lock is still missing some checksums:

> No hash was found while vendoring the git dependency biscuit-0.6.0-beta1

I'd assume it's the crates mentioned in https://github.com/wireapp/rusty-jwt-tools/issues/53, and might be fixed by switching from

```
 [patch.crates-io.biscuit]                                                              
   6  git = "https://github.com/beltram/biscuit"                                             
   7  tag = "v0.6.0-pre.core-crypto-0.6.0"
```

To an explicit
```
[dependencies.biscuit]
git = https://github.com/beltram/biscuit.git
rev = 36b6f30964142f0ca5bc17c908e8b2ad78febaf6
```

section (and similarly for the other deps where we currently use the patches mechanism).

The `Cargo.lock` file(s) should then contain a `checksum` field for these crates.

**Comment by beltram** [comment]
I pinned revisions instead of tags. Does it work better ?

**Comment by flokli** [comment]
No, Cargo.lock is still missing the checksums.

**Comment by flokli** [comment]
So apparently in both cases the checksums don't end up getting added to `Cargo.lock`, which is why tools like `crate2nix` do populate a `crate-hashes.json` in addition to the `Cargo.lock`.

I'll see if I can get it to work on the wire-server side, and will update you here once I got it working :+1:

**Comment by beltram** [comment]
Fixed by getting rid of ring 39d56d53b3b0f84432bb049d8de5b2a94e03b4a8 and build (manually) Cargo.lock in ffi crate

**Pull request closed without merging**
