### PR TITLE
fix: Haskell tests

### PR DESCRIPTION
**Pull request by battermann**

### CODE REVIEW

**Comment by istankovic** [comment]
@battermann is this draft PR still relevant? What's the plan here?

**Comment by battermann** [comment]
> @battermann is this draft PR still relevant? What's the plan here?

The Haskell FFI tests are failing in this PR. But they are failing on main as well. So they should be fixed at some point. Can we keep it and fix when we find the time, or merge it now?

**Comment by istankovic** [comment]
> The Haskell FFI tests are failing in this PR. But they are failing on main as well. So they should be fixed at some point. Can we keep it and fix when we find the time, or merge it now?

Oh, I'd actually love if we had a working test for Haskell FFI in our CI. I'm curious, do you know why are those tests failing and how hard would it be to fix them? (I'm afraid it's been quite a while since I last touched Haskell...)

Also, before we can merge this, the commits need to be cleaned up and, in particular, the merge commits should not be part of the PR.

**Comment by istankovic** [comment]
Obsoleted by #233.
Thanks for the help with the test, @battermann.

**Pull request closed without merging**
