### PR TITLE
chore: replace instant with web-time & remove nix [WPB-14399]

### PR DESCRIPTION
**Pull request by typfel**
# What's new in this PR

----
##### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by istankovic** [comment]
Could you please also remove `shell.nix` and `.envrc` now that those are no longer needed?

**Comment by typfel** [comment]
> Could you please also remove `shell.nix` and `.envrc` now that those are no longer needed? Also, the README needs updating now that we no longer need nix.

We don't want to keep for running the tests locally?

**Comment by istankovic** [comment]
> > Could you please also remove `shell.nix` and `.envrc` now that those are no longer needed? Also, the README needs updating now that we no longer need nix.
> 
> We don't want to keep it for running the tests locally?

Well, I see no reason for that if the CI also doesn't use nix. It's just an extra dependency to install locally. :shrug:

**Review by istankovic — APPROVED** [review]
:wine_glass:

**Pull request merged**
