### PR TITLE
chore(Cargo): add Cargo.lock

### PR DESCRIPTION
**Pull request by flokli**
In addition to library code, we ship binaries here, so it's recommended to ship a `Cargo.lock` according to
https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html.

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Comment by flokli** [comment]
Also see https://github.com/wireapp/wire-server/pull/2989/commits/6dd43a3f1c92e2fe2efbd2e2d0d243ed0456727c for context.

**Comment by beltram** [comment]
@flokli I get this but this will cause troubles on our side in this case. We barely use this as a binary (in fact we won't in the future). Adding a Cargo.lock here will disrupt this project's main consumer: [core-crypto](https://github.com/wireapp/core-crypto).  

Can't the Nix formula somehow ignore Cargo.lock 's hash ?

**Comment by flokli** [comment]
I get it, but it's a bit more complicated. It'd be sufficient to just have a `Cargo.lock` file for the`ffi` crate, but as this is a cargo workspace there's only one global `Cargo.lock`.

`ffi` is not a library, as there's no more "other Cargo"  which could generate one.

It should probably be its own crate, in a separate repo, with a lockfile maintained there.

**Comment by beltram** [comment]
> It should probably be its own crate, in a separate repo, with a lockfile maintained there.

Yes, let's do that instead

**Comment by flokli** [comment]
Thanks, can you do this?

**Comment by beltram** [comment]
Superseded by #54

**Comment by battermann** [comment]
please don't delete this branch!

**Pull request closed without merging**
